# Generated by Django 4.2.4 on 2023-09-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personevent',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personEventCreater', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='teamevent',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamEventCreater', to='main.team'),
        ),
    ]
