# Generated by Django 4.2.4 on 2023-09-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_personevent_creater_alter_teamevent_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.team'),
            preserve_default=False,
        ),
    ]
