# Generated by Django 4.2.4 on 2023-10-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.category'),
            preserve_default=False,
        ),
    ]
