# Generated by Django 4.2.4 on 2023-10-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_team_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_agreed', models.BooleanField()),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_profile', to='main.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_profile', to='main.profile')),
            ],
        ),
    ]
