# Generated by Django 4.2.4 on 2023-10-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teamrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='is_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
